language: dart
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
<<<<<<< HEAD
#  - eval echo `<travis.conf` | xargs flutter build
=======
>>>>>>> parent of 7f048bf... Move API_KEYS to environment variables
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache